name: Docker Image CI

on:
  push:
    branches: [ feature/*, bugfix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate go.mod
      run: docker run --rm -v ${PWD}:/src -w /src golang:1.14.3-alpine go mod init example
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        
    - name: Generate go.sum
      run: docker run --rm -v ${PWD}:/src -w /src golang:1.14.3-alpine go mod tidy
      
    - name: Build test image
      run: docker build . --target unit-test --tag example-test:${{steps.vars.outputs.tag}}
      
    - name: Run tests
      run: docker run example-test:${{steps.vars.outputs.tag}}
