name: Docker Image CI

on:
  push:
    branches: [ feature/*, bugfix/* ]
  pull_request:
    branches: [ main, develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
        driver: docker

    - name: Build test container
      run: docker build . --target unit-test --tag example-test
       
    - name: Run tests
      run: docker run example-test
  
